INSERT INTO CONSUMER_ORDER VALUES(1, 'tom',35, '悬崖之上');
INSERT INTO CONSUMER_ORDER VALUES(2, 'tom',45, '无极');
INSERT INTO CONSUMER_ORDER VALUES(3, 'tom',55, '猫和老鼠');
INSERT INTO CONSUMER_ORDER VALUES(4, 'tom',15, '波妞');